# Basicamento o deployment tem a mesma estrutura do replicaset
apiVersion : apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 6
  # Funcionalidade do selector
  selector: 
    matchLabels:
      app: web
    template:
      metadata:
        # O nome da label tem que igual ao do replica set
        labels:
          app: web
      spec:
        containers:
          - name: web
            image: kubedevio/web-page:blue
            ports:
              - containerPort: 80
...

# Utilizando service
apiVersion : v1
kind: Service
metadata:
  name: web
spec:
    selector:
      app: web
    ports:
        - port: 80
          protocol: TCP
          name: http
    type: NodePort